name: Tests

on: push

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [3.7, 3.8]
    services:
      edgedb:
        image: edgedb/edgedb:latest
        ports:
          - 5656:5656
    steps:
      - uses: actions/checkout@master
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/cache@v1
        id: cache-poetry
        with:
          path: ~/.cache/pip
          key: get-poetry-${{ runner.os }}-py-${{ matrix.python-version }}
          restore-keys: |
            get-poetry-${{ runner.os }}-py-
            get-poetry-${{ runner.os }}-
      - name: Install poetry
        if: steps.cache-poetry.outputs.cache-hit != 'true'
        run: |
          pip install poetry==1.0
          poetry config virtualenvs.in-project true
      - uses: actions/cache@v1
        id: cache-deps
        with:
          path: .venv
          key: venv-${{ runner.os }}-py-${{ matrix.python-version }}-poetry-${{ hashFiles('poetry.lock') }}
      - name: Install dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: |
          poetry install
      - name: Run tests
        env:
          EDGEDB_DSN: edgedb://edgedb@localhost/edgedb
        run: |
          # sleep for 1 minute for EdgeDB bootstraping.
          # TODO: remove after release cli with --wait-until-available
          sleep 60
          source .venv/bin/activate
          ./scripts/test --cov-report=xml
      - uses: codecov/codecov-action@v1.0.6
